### ISSUE TITLE
Possible dependency failure

### ISSUE THREAD

**Issue by scriptonist** [fsouza/go-dockerclient#736]
- I've started a project
- Imported `github.com/fsouza/go-dockerclient`
-  Ran `dep ensure`

On trying to run the program, I'm encoutering the following error
```
../../vendor/github.com/docker/docker/opts/address_pools.go:15:12: undefined: ipamu
tils.NetworkToSplit
```
Anybody experienced this issue before ?

**Comment by PMoneda** [comment]
I have the same problem;

1) dep ensure -add github.com/fsouza/go-dockerclient
2) go run main.go
3) dep error

**Comment by scriptonist** [comment]
Don't know if It's a hack, but got it working after adding the following in my `Gopkg.toml` file.
```
[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"
```

**Comment by fsouza** [comment]
Sorry @scriptonist @PMoneda, this issue has been fixed on master but I need to tag a new release, my bad. Just tagged 1.2.1, so the ``[[override]]`` won't be necessary.

**Comment by davidkhala** [comment]
The problem still exist in 1.2.1

**Comment by fsouza** [comment]
@davidkhala can you post the error you're seeing?

I was able to do the following:

```
$ mkdir $GOPATH/src/sample
$ cat >$GOPATH/src/sample/sample.go
package sample

import "github.com/fsouza/go-dockerclient"

var Client *docker.Client
^-D
$ cd $GOPATH/src/sample
$ dep init
$ dep ensure
$ go build
```

**Comment by rfay** [comment]
I see this in 1.2.2 as well.

**Comment by rfay** [comment]
@fsouza  This simple gist demonstrates the problem. It's the exact thing you suggested above in https://github.com/fsouza/go-dockerclient/issues/736#issuecomment-401340792

dep v0.4.1
golang 1.10.3

Please reopen this issue, it's not resolved.

**Comment by fsouza** [comment]
@rfay I still can't reproduce. Can you run dep commands in verbose mode?

```
$ mkdir $GOPATH/src/sample
$ cat >$GOPATH/src/sample/sample.go
package sample

import "github.com/fsouza/go-dockerclient"

var Client *docker.Client
^-D
$ cd $GOPATH/src/sample
$ dep init -v
$ dep ensure -v
$ go build
```

Also, what's the output of ``go version``? And what does your Gopkg.toml & Gopkg.lock look like after you run those commands?

Last, but not least, can you try with the ``master`` version of ``dep`` (``go get -u github.com/golang/dep/cmd/dep``)? That's what I'm currently using. dep 0.4.1 has been released in January and a **LOT** has happened since then: https://github.com/golang/dep/compare/v0.4.1...master

**Comment by rfay** [comment]
Shoot, I failed to paste the link to the gist, sorry, https://gist.github.com/rfay/758f9462c30a28c43b1a5ecaf02964a0 - it has the Gopkg.lock that got created. That's exactly the same thing you posted.

go version: go version go1.10.3 darwin/amd64

In the gist directory, with dep v0.4.1:
```
rm Gopkg.toml
dep ensure
go build
# sample/vendor/github.com/docker/docker/opts
vendor/github.com/docker/docker/opts/address_pools.go:15:12: undefined: ipamutils.NetworkToSplit
```

Did the same thing with current master of dep:
```
dep version
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```
Exact same behavior.

**Comment by fsouza** [comment]
@rfay coool, thanks for sharing that. can you also share the output of `dep ensurve -v`? I'll dig into that.

**Comment by fabianem** [comment]
@fsouza do you have maybe any updates regarding this issue?
Because I am facing now a similar problem - have this included in my **Gopkg.toml**:
```
[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.3.1"
```

And trying to run a test I am getting this error message:
`[root_project]/vendor/github.com/fsouza/go-dockerclient/internal/archive
../vendor/github.com/fsouza/go-dockerclient/internal/archive/archive.go:74:20: undefined: idtools.Identity`

And I checked my local file **[root_project]\vendor\github.com\docker\docker\pkg\idtools\idtools.go** and indeed I have no **Identity** struct defined. I guess its because of the revision number I hard coded for **github.com/docker/docker**.

Do you have maybe an idea how to fix this?
Thanks!

**Comment by fsouza** [comment]
@fabianem sorry about that. Can you try removing the ``github.com/docker/docker`` override and using go-dockerclient's master? Or, if you can link me to a repo, I can give it a shot too.

**Comment by fabianem** [comment]
@fsouza unfortunately removing `github.com/docker/docker` and using go-dockerclient's master didn't solve the problem. But I finally figured a problem, which makes kinda solution - I am quite new to golang and especially dep, so not quite sure if this is the best approach:

**Gopkg.toml**:

```
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[[override]]
  branch = "master"
  name = "github.com/hpcloud/tail"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.2"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "1.3.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  branch = "master"

[[override]]
  name = "github.com/docker/libnetwork"
  branch = "master"
```
What I did now is added for `github.com/docker/docker` `branch = "master"` instead of `revision = "a422774e593b33bd287d9890544ad9e09b380d8c"`. But this brought me to the next problem, some dependency issue with `github.com/docker/libnetwork`. Unfortunately this repository stopped releasing new versions but development continues. And dep automatically tried to pull the newest release (which is over 2years old) and of course some changes were missing. So I did include also an override for `github.com/docker/libnetwork` with `branch = "master"`.
Finally, now it seems to work 😃 

@fsouza thanks for your help :) I would like to share my repo with you but the project I am working on is for a client and in a private repo - I am integrating Hyperledge fabric into a SaaS platform and developing currently fabric chaincodes in golang :)

**Comment by fsouza** [comment]
@fabianem awesome, I'm glad you were able to figure it out!

**Comment by davidkhala** [comment]
https://github.com/davidkhala/fabric-common-chaincode-golang

This is a reference for Hyperledger fabric developer

At least for release-1.4, a quick fix could be 

 `
[[constraint]]
  name = "github.com/hyperledger/fabric"
  branch = "release-1.4"
# TODO jira issue https://jira.hyperledger.org/browse/FAB-10936

#FIXME if test passed, please clean up this 'fsouza/go-dockerclient' section
[[override]]
    name = "github.com/fsouza/go-dockerclient"
    version = "=1.2.1"
`
